# Pipeline YAML for PR

jobs:
- job: Windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    buildConfiguration: 'Release'
  steps:
  - task: BatchScript@1
    displayName: 'Run script build.cmd'
    inputs:
      filename: build.cmd
      arguments: '-verbose -configuration $(buildConfiguration)'
      modifyEnvironment: false
      failOnStandardError: true

  - task: CmdLine@1
    displayName: 'Delete stale pdb files'
    inputs:
      filename: del
      arguments: '/S /F *.pdb'
      workingFolder: '$(SystemRoot)'
    continueOnError: true
    condition: always()

  - task: BatchScript@1
    displayName: 'Run Unit Tests'
    inputs:
      filename: test.cmd
      arguments: '-verbose -configuration $(buildConfiguration)'
      modifyEnvironment: false
      failOnStandardError: true
      
  - task: BatchScript@1
    displayName: 'Run Acceptance Tests'
    inputs:
      filename: test.cmd
      arguments: '-verbose -configuration $(buildConfiguration) -p AcceptanceTests -f net451'
      modifyEnvironment: false
      failOnStandardError: true
      
  - task: BatchScript@1
    displayName: 'Run Platform Tests'
    inputs:
      filename: test.cmd
      arguments: '-verbose -configuration $(buildConfiguration) -p platformtests'
      modifyEnvironment: false
      failOnStandardError: true
            
  - task: BatchScript@1
    displayName: 'Run Smoke Tests'
    inputs:
      filename: test.cmd
      arguments: '-verbose -configuration $(buildConfiguration) -p smoke'
      modifyEnvironment: false
      failOnStandardError: true
      
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **\*.trx'
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**\*.trx'
    condition: succeededOrFailed()
    
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
      buildConfiguration: 'Release'
  steps:
  - script: ./build.sh -DotNetBuildFromSource -c Release
    displayName: './build.sh -c $(buildConfiguration)'
   
