# PR pipeline for TestPlatform

resources:
- repo: self
  clean: true
queue:
  name: VSEng-MicroBuildVS2017
  demands: 
  - DotNetFramework
  - Cmd
  - msbuild
  - visualstudio

variables:
  BuildConfiguration: 'release'
  BuildTargetRuntime: 'win7-x64'
steps:

- task: BatchScript@1
  displayName: 'Run script build.cmd'
  inputs:
    filename: build.cmd

    arguments: '-verbose -configuration release'

    modifyEnvironment: false

    failOnStandardError: true


- task: CmdLine@1
  displayName: 'Delete stale pdb files'
  inputs:
    filename: del

    arguments: '/S /F *.pdb'

    workingFolder: '$(SystemRoot)'

  continueOnError: true
  condition: always()

- task: BatchScript@1
  displayName: 'Run script test.cmd'
  inputs:
    filename: test.cmd

    arguments: '-verbose -configuration $(BuildConfiguration)'

    modifyEnvironment: false

    failOnStandardError: true


- task: PublishTestResults@2
  displayName: 'Publish Test Results **\*.trx'
  inputs:
    testResultsFormat: VSTest

    testResultsFiles: '**\*.trx'

  condition: succeededOrFailed()



